"""Add versioned POD product copy generated by the copy engine."""

import sqlalchemy as sa

from alembic import op

revision = "20261007_0019"
down_revision = "20261007_0018"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE pod_product_copies (
            id uuid PRIMARY KEY,
            product_id uuid NOT NULL REFERENCES pod_products(id) ON DELETE RESTRICT,
            generation_job_id uuid REFERENCES image_jobs(id) ON DELETE RESTRICT,
            version integer NOT NULL,
            locale varchar(16) NOT NULL DEFAULT 'en-US',
            product_title varchar(200) NOT NULL,
            product_description text NOT NULL,
            selling_points jsonb NOT NULL DEFAULT '[]'::jsonb,
            search_keywords jsonb NOT NULL DEFAULT '[]'::jsonb,
            content_warnings jsonb NOT NULL DEFAULT '[]'::jsonb,
            prompt_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
            status varchar(16) NOT NULL DEFAULT 'active',
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_pod_product_copies_status CHECK (status IN ('active', 'archived')),
            CONSTRAINT uq_pod_product_copies_product_version UNIQUE (product_id, version)
        )
    """)
    op.execute(
        "CREATE UNIQUE INDEX uq_pod_product_copies_product_active "
        "ON pod_product_copies (product_id) WHERE status = 'active'"
    )
    op.create_index(
        "ix_pod_product_copies_product_created",
        "pod_product_copies",
        ["product_id", "created_at", "id"],
    )
    op.execute(
        sa.text("""
            INSERT INTO operation_catalog (id, code, name, engine_type, queue_name, enabled, timeout_seconds, max_attempts)
            VALUES (CAST(:id AS uuid), :code, :name, 'sub2api', 'image-jobs', true, :timeout, :attempts)
            ON CONFLICT (code) DO NOTHING
        """).bindparams(
            id="f0000000-0000-4000-8000-000000000033",
            code="pod.copy.generate",
            name="AI 商品文案",
            timeout=240,
            attempts=2,
        )
    )
    op.execute(
        sa.text("""
            INSERT INTO operation_prices (id, operation_id, version, base_points, parameter_rules, effective_from, reason)
            SELECT CAST(:price_id AS uuid), id, 1, :points, '{}'::jsonb, now(), 'POD copy engine initial price'
            FROM operation_catalog WHERE code = :code
            AND NOT EXISTS (SELECT 1 FROM operation_prices WHERE operation_id = operation_catalog.id)
        """).bindparams(
            price_id="f0000000-0000-4000-8000-000000000034",
            points=3,
            code="pod.copy.generate",
        )
    )
    op.execute(
        sa.text("INSERT INTO schema_migrations (version) VALUES (:version)").bindparams(
            version=revision
        )
    )


def downgrade() -> None:
    op.execute("UPDATE operation_catalog SET enabled = false WHERE code = 'pod.copy.generate'")
    op.execute(
        sa.text("DELETE FROM schema_migrations WHERE version = :version").bindparams(
            version=revision
        )
    )
